### ISSUE TITLE
Trying to build in Linux Ubuntu 16

### ISSUE THREAD

**Issue by KhmerRun** [dime-coin/dimecoin#1]
Hello,

I was trying to compile (make -f makefile.unix) this under Linux and error:

/home/xxxxxxxxxx/pools/pool-dimecoin-daemon/dimecoin/src/leveldb/libleveldb.a(options.o): In function `leveldb::Options::Options()':
/home/xxxxxxxxxx/pools/pool-dimecoin-daemon/dimecoin/src/leveldb/util/options.cc:17: undefined reference to `leveldb::Env::Default()'
collect2: error: ld returned 1 exit status
makefile.unix:195: recipe for target 'dimecoind' failed
make: *** [dimecoind] Error 1

Regards,

**Comment by simonerom** [comment]
We were able to build the linux wallet on the latest Ubuntu desktop (16.04). Not sure about the error you are getting: you may want to try building leveldb first:

```
cd dimecoin/src/leveldb
make clean
make leveldb.a libmemenv.a
```

Also you may want to try this into the leveldb folder as well:
```
chmod +x build_detect_platform
chmod 775 *
```

**Comment by simonerom** [comment]
We will add Ubuntu build instructions soon.

**Comment by simonerom** [comment]
So could you build it?

**Comment by KhmerRun** [comment]
Yes, build was successful after chmod +x build_detect_platform

**Comment by simonerom** [comment]
Ok thank you.
Btw I noticed there is a issue with Unity that leads to missing menu bar and tray icon in Ubuntu. I experienced it on Ubuntu 16.04, while it's not happening anymore on Ubuntu 17.04. Just in case you got the same problem. It can't be fixed on our side and anyway it seems Unity is being replaced by Gnome starting from Ubuntu 17.

**Comment by KhmerRun** [comment]
Hi, I didn't know that because I did via terminal (SSH) and no GUI.

**Comment by halfirish83** [comment]
Ok, thank you for your feedback.
