### ISSUE TITLE
No Block Source Available - Mac QT

### ISSUE THREAD

**Issue by tomboslice** [dime-coin/dimecoin#17]
Hello, 

Recently installed the Mac Qt wallet and after loading I am met with the error "no block source available". Any thoughts on this? 

![screen shot 2018-05-16 at 3 26 07 pm](https://user-images.githubusercontent.com/39348296/40139412-c6553d8c-591d-11e8-8d07-6063d3b9b9fc.png)

**Comment by Biotonne86** [comment]
Same issue here, trying to download the bootstrap now:
https://github.com/dime-coin/dimecoin/wiki/Speed-up-the-Syncing-Process

Could you solve the problem?

**Comment by PraiseDuarte** [comment]
Hey @Biotonne86 - I recently made a new blockchain snapshot and thought I had updated it in the wiki but I just realized I must have forgot. It's in there now, and I want to add that I was helping another community member that had the same issue as you – they had done 3 fresh installs with the older blockchain previously, but once they tried using this new snapshot I took from my Macbook everything was good to go for them.

Not sure if it's a coincidence, but I would definitely try it out. I'm definitely interested in hearing how it goes so please let me know

**Comment by CryptoAxl** [comment]
Hi,
Several Mac users had the same issue, and it seems that you are forced to use a dimecoin.conf file from the beginning, with last node addresses. It can be found here : https://github.com/dime-coin/dimecoin/wiki/Update-network-nodes-%28dimecoin.conf%29

Directory where to copy that file on Mac : 
Users/[YourName]/library/application Support/Dimecoin

A better version of the wallet will be available soon. The explanation above has fixed the syncing issue of people who had it on Mac. However, we will close that issue when it doesn't happen anymore on the next version.

**Comment by Biotonne86** [comment]
Hi, and sorry, that i missed to post a fix for the problem. I just forgot about this Github comment... ;(

Here is a solution :)

Start Mac Wallet, then go to menu --> help --> debug window --> console. Type in:
"addnode 71.84.252.83 add"
Then type in: "getpeerinfo"

The text below should show up and the wallet should start to sync soon.

"addr" : "46.101.170.182:11931",
"services" : "00000001",
"lastsend" : 1527786782,
"lastrecv" : 1527786782,
"bytessent" : 19372,
"bytesrecv" : 18176,
"conntime" : 1527786780,
"version" : 70003,
"subver" : "/dimecoin:1.7.2/",
"inbound" : false,
"startingheight" : 2895915,
"banscore" : 0,
"syncnode" : true

If nothing shows up, then try any of the peers below:
addnode=35.196.157.31 addnode=177.85.98.203 addnode=101.186.114.252 addnode=109.184.21.39 addnode=121.131.77.68 addnode=125.13.35.50 addnode=125.143.153.191 addnode=125.215.98.139 addnode=169.0.91.32 addnode=188.232.223.142 addnode=188.44.71.97 addnode=190.213.20.174 addnode=190.213.20.174 addnode=207.148.24.217 addnode=24.237.24.171 addnode=24.99.111.87 addnode=47.41.234.219 addnode=5.88.56.136 addnode=58.88.50.119 addnode=68.224.75.229 addnode=68.44.57.88 addnode=69.133.137.121 addnode=72.190.176.200 addnode=73.200.44.186 addnode=73.238.25.173 addnode=78.188.109.193 addnode=94.11.167.177 addnode=94.176.18.250 addnode=96.50.235.1 addnode=98.118.167.57

**Comment by CryptoAxl** [comment]
Hey guys, please have a try at latest Mac 1.9-beta1 wallet and let me know if u still have issues.
