### ISSUE TITLE
CreateNewBlock: TestBlockValidity failed: bad-diffbits

### ISSUE THREAD

**Issue by laakie** [dime-coin/dimecoin#58]
<html>
<body>
<div class="row" style="box-sizing: border-box; margin-right: -15px; margin-left: -15px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="panel panel-info" style="box-sizing: border-box; margin-bottom: 20px; background-color: rgb(255, 255, 255); border: 1px solid rgb(80, 80, 124); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.05) 0px 1px 1px;"><div class="panel-body" style="box-sizing: border-box; padding: 15px; color: rgb(80, 80, 124); background-color: white; border-color: red;">

ERROR: CreateNewBlock: TestBlockValidity failed: bad-diffbits, incorrect difficulty: block pow=Y bits=1a02e2d1 calc=1b0864bd (code 16)
--

</div></div></div><div class="row" style="box-sizing: border-box; margin-right: -15px; margin-left: -15px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="panel panel-info" style="box-sizing: border-box; margin-bottom: 20px; background-color: rgb(255, 255, 255); border: 1px solid rgb(80, 80, 124); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.05) 0px 1px 1px;"><div class="panel-heading" style="box-sizing: border-box; padding: 10px 15px; border-bottom: 1px solid rgb(80, 80, 124); border-top-left-radius: 3px; border-top-right-radius: 3px; color: rgb(80, 80, 124); background-color: white; border-top-color: rgb(80, 80, 124); border-right-color: rgb(80, 80, 124); border-left-color: rgb(80, 80, 124);"><i class="fa fa-money fa-fw" style="box-sizing: border-box; display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; line-height: 1; font-family: FontAwesome; font-size: inherit; text-rendering: auto; -webkit-font-smoothing: antialiased; transform: translate(0px, 0px); width: 1.28571em; text-align: center;"></i></div></div></div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by Dhop14** [comment]
We are currently working on resolving this error. Essentially at the fork height there was a chain split that is causing some confusion between the 2.0.0 nodes that did not update in time and the new 2.1.0 nodes. 

Additionally, we will be making a few changes to the retarget algorithm to ensure smoother interoperability between POW/POS and sunset all nodes on the 70005 protocol to make syncing and finding the correct chain easier.
