### ISSUE TITLE
Sync causes assertion failure

### ISSUE THREAD

**Issue by mtl1979** [dime-coin/dimecoin#78]
**Expected behavior**

Sync finishes.

**Actual behavior**

Assertion failure in https://github.com/dime-coin/dimecoin/blob/master/src/checkpointsync.cpp#L218

**To reproduce**

Happens sometimes after closing the GUI wallet and restarting Windows. Does not happen if syncing from block 0.

**System information**

* Version 2.2.0.0 (gdb33ca697599d38e94c49bdb5d7ed6e7a9e67f43) 64-bit

* Windows 11, Intel i5-9600k, 32 GB ram, 1 TB m.2 flash module on motherboard

**Comment by Dhop14** [comment]
This issue should be resolved with this commit [62b85a6](https://github.com/dime-coin/dimecoin/commit/62b85a637ebb6b2a1dbabb2b9355a743c73f2f28). 

We are preparing to merge the latest changes from the hotfix branch into master shortly. These changes will address some other stability issues related to the dual consensus. Once the merge is complete, we will mark the next stable release of Dimecoin Core.
